### ISSUE TITLE
Unnecessary CPU usage during mouse movements

### ISSUE THREAD

**Issue by 3rd3** [kasper/phoenix#176] opened 2017-04-09 21:02 UTC
Phoenix causes 1-2% CPU use when moving the mouse. This does not seem to be necessary as I don't make use of these events in my Phoenix configuration.

**Comment by kasper** [comment] 2017-04-10 05:32
Duplicate of #170. I will optimise this at some point.

**Closed by kasper** 2017-04-10 05:32 UTC
