### ISSUE TITLE
Phoenix crashes on start for some keyboard layouts

### ISSUE THREAD

**Issue by metakirby5** [kasper/phoenix#166] opened 2017-02-13 04:46 UTC
- Version: 2.5 (59)
- macOS: 10.12.3 (16D32)

Occurs if a `Key.on` bind is executed in the config with only a Japanese input source.

[Crash Log](https://ptpb.pw/R9yk.crash)

**Comment by kasper** [comment] 2017-02-13 19:04
It crashes on every start? Do you use some custom keyboard layout or modify it with some app or kernel extension?

**Comment by metakirby5** [comment] 2017-02-13 19:22
Your first guess was spot-on! I forgot I had removed my U.S. keyboard layout and replaced it with the Japanese romaji layout, since I was using Japanese as another input source anyways. Once I added U.S. back, it stopped crashing on startup. Thanks for the quick advice :)

I think it would be helpful to add some sort of diagnostic message though, as Phoenix fails silently when this happens.

**Comment by kasper** [comment] 2017-02-14 06:55
Yes, definitely. It’s evident that its missing a guard to prevent the crash and a diagnostic message would be helpful. Thanks for the report and good that you got it sorted!

**Comment by kasper** [comment] 2018-06-08 12:08
Closed as a duplicate of #196.

**Closed by kasper** 2018-06-08 12:08 UTC
