### ISSUE TITLE
`otherWindowsOnSameScreen` takes many time

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#21] opened 2015-03-02 01:51 UTC
Sometime I use `Window.focusedWindow().otherWindowsOnSameScreen()`,it takes about 5 seconds.

log code:

```
  var start = new Date().getTime();
  var otherWindowsOnSameScreen = Window.focusedWindow().otherWindowsOnSameScreen();
  api.log('windowsOnOtherScreen 0.1: ' + (new Date().getTime() - start));

```

log from Console.

```
3/2/15 09:46:10.942 Phoenix[50589]: windowsOnOtherScreen 0.1: 4922
```

I cannnot reproduce it always, it happened about 10+ times one day.

**Comment by alswl** [comment] 2015-05-30 09:10
it's spin report.

```
Date/Time:       2015-05-30 16:55:17 +0800
OS Version:      10.10.3 (Build 14D136)
Architecture:    x86_64h
Report Version:  21

Command:         Phoenix
Path:            /opt/homebrew-cask/*/Phoenix.app/Contents/MacOS/Phoenix
Version:         1.2 (1.2)
PID:             40685

Event:           spin-lite
Duration:        3.90s (process was unresponsive for 2 seconds before sampling)
Steps:           40 (100ms sampling interval)

Hardware model:  MacBookPro11,1
Active cpus:     4

Fan speed:       1288 rpm

Heaviest stack for the main thread of the target process:
  40  start + 1 (libdyld.dylib + 13769) [0x7fff9ad2a5c9]
  40  NSApplicationMain + 1832 (AppKit + 13140) [0x7fff9a1a8354]
  40  -[NSApplication run] + 711 (AppKit + 552040) [0x7fff9a22bc68]
  40  -[NSApplication sendEvent:] + 2104 (AppKit + 1429890) [0x7fff9a302182]
  40  SendEventToEventTarget + 40 (HIToolbox + 122038) [0x7fff95a9ecb6]
  40  SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 386 (HIToolbox + 32686) [0x7fff95a88fae]
  40  DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1260 (HIToolbox + 35692) [0x7fff95a89b6c]
  40  PHHotKeyCarbonCallback + 175 (Phoenix + 10848) [0x101b10a60]
  40  __27-[PHConfigLoader setupAPI:]_block_invoke_6 + 61 (Phoenix + 29663) [0x101b153df]
  40  -[JSValue callWithArguments:] + 286 (JavaScriptCore + 2018414) [0x7fff8e480c6e]
  40  JSObjectCallAsFunction + 691 (JavaScriptCore + 396819) [0x7fff8e2f4e13]
  40  JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 62 (JavaScriptCore + 397022) [0x7fff8e2f4ede]
  40  JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 462 (JavaScriptCore + 397502) [0x7fff8e2f50be]
  40  JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 35 (JavaScriptCore + 3790307) [0x7fff8e6315e3]
  40  callToJavaScript + 311 (JavaScriptCore + 4297873) [0x7fff8e6ad491]
  40  llint_entry + 22657 (JavaScriptCore + 4321079) [0x7fff8e6b2f37]
  40  llint_entry + 22657 (JavaScriptCore + 4321079) [0x7fff8e6b2f37]
  40  llint_entry + 22753 (JavaScriptCore + 4321175) [0x7fff8e6b2f97]
  40  JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*) + 452 (JavaScriptCore + 386004) [0x7fff8e2f23d4]
  40  long long JSC::APICallbackFunction::call<JSC::ObjCCallbackFunction>(JSC::ExecState*) + 517 (JavaScriptCore + 4400901) [0x7fff8e6c6705]
  40  JSC::objCCallbackFunctionCallAsFunction(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) + 262 (JavaScriptCore + 4398086) [0x7fff8e6c5c06]
  40  JSC::ObjCCallbackFunctionImpl::call(JSContext*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) + 417 (JavaScriptCore + 4399217) [0x7fff8e6c6071]
  40  -[NSInvocation invoke] + 290 (CoreFoundation + 243218) [0x7fff8e7ed612]
  40  __invoking___ + 140 (CoreFoundation + 243644) [0x7fff8e7ed7bc]
  40  -[PHWindow otherWindowsOnSameScreen] + 42 (Phoenix + 15428) [0x101b11c44]
  40  +[PHWindow visibleWindows] + 28 (Phoenix + 13957) [0x101b11685]
  40  +[PHWindow allWindows] + 239 (Phoenix + 13690) [0x101b1157a]
  40  -[PHApp allWindows] + 91 (Phoenix + 22950) [0x101b139a6]
  40  AXUIElementCopyAttributeValues + 824 (HIServices + 124310) [0x7fff9c8b4596]
  40  _AXMIGCopyAttributeValues + 361 (HIServices + 167574) [0x7fff9c8bee96]
  40  mach_msg_trap + 10 (libsystem_kernel.dylib + 70878) [0x7fff9bf0f4de]
 *40  ipc_mqueue_receive_continue + 0 (kernel + 1148928) [0xffffff8000318800]

  Binary Images:
         0x101b0e000 -        0x101b19fff  org.degutis.Phoenix 1.2 (1.2)               <2ECAF7A5-D93B-35F3-8586-CFF5858134B0>  /opt/homebrew-cask/*/Phoenix.app/Contents/MacOS/Phoenix
      0x7fff8e294000 -     0x7fff8e7a9fff  com.apple.JavaScriptCore 10600 (10600.5.10) <ED4CABC6-0952-3E28-A3CD-32CA5CE22252>  /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
      0x7fff8e7b2000 -     0x7fff8eb4afff  com.apple.CoreFoundation 6.9 (1153.18)      <5C0892B8-9691-341F-9279-CA3A74D59AA0>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
      0x7fff95a81000 -     0x7fff95d86fff  com.apple.HIToolbox 2.1.1 (758.7)           <6711FAA9-904A-3B49-9665-FC8D13B93C42>  /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
      0x7fff9a1a5000 -     0x7fff9ad26fff  com.apple.AppKit 6.9 (1347.57)              <B214D528-7D1C-39B2-BE36-821D417A0297>  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
      0x7fff9ad27000 -     0x7fff9ad2afff  libdyld.dylib (353.2.1)                     <9EACCA38-291D-38CC-811F-7E9D1451E2D3>  /usr/lib/system/libdyld.dylib
      0x7fff9befe000 -     0x7fff9bf1bfff  libsystem_kernel.dylib (2782.20.48)         <EAFD7BD0-0C30-3E7D-9528-F9916BA0167C>  /usr/lib/system/libsystem_kernel.dylib
      0x7fff9c896000 -     0x7fff9c8e0fff  com.apple.HIServices 1.22 (522.1)           <E8BD41E4-7747-3CAF-807A-5CA9AD16B525>  /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
 *0xffffff8000200000 - 0xffffff80009fffff  kernel (2782.20.48)                         <4B3A11F4-77AA-3D27-A22D-81A1BC5B504D>  /System/Library/Kernels/kernel

```

**Comment by kasper** [comment] 2015-08-05 13:55
@alswl I’m refactoring the code and will take a look into this sometime along the way. Do you have any steps to reproduce this reliably?

**Comment by alswl** [comment] 2015-08-06 02:21
@kasper 
I cannot reproduce reliably, but sometimes.

use my configuration https://github.com/alswl/.oOo./blob/master/.phoenix.js .
open many windows, (10+), use `mod+j` switch window, it will come soon

**Comment by jasonm23** [comment] 2015-08-06 02:31
Just a thought, are there any applications' windows which seem to have this problem more than others?

**Comment by jasonm23** [comment] 2015-08-06 02:32
Also let us know the OS X version - thank you

**Comment by alswl** [comment] 2015-08-06 02:42
No, every App can meet this problem.

Yosemite 10.10.4 (14E46)

On Thu, Aug 6, 2015 at 10:33 AM, JasonM23 <notifications@github.com> wrote:

> Also let us know the OS X version - thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kasper/phoenix/issues/21#issuecomment-128217305>.
>



-- 
-----------------------------------------
alswl
Blog: http://log4d.com/
Mail: alswlx[a]gmailDOTcom
-----------------------------------------

**Comment by kasper** [comment] 2015-08-06 07:02
@alswl Great, thanks for the information! I’ll see whether I can improve this.

**Comment by kasper** [comment] 2015-08-31 09:21
@alswl Could you test this against 2.0? I opened more than 20+ windows and repeated the call multiple times in sequence. Only the first invocation is relatively slower than the other calls. When I opened more than 40+ windows the results are in line with the previous observations. Maybe this has been fixed with the refactor?

```js
Phoenix.bind('e', [ 'ctrl', 'shift' ], function () {

   var start = new Date().getTime();
   var otherWindowsOnSameScreen = Window.focusedWindow().otherWindowsOnSameScreen();
   Phoenix.log('Time: ' + (new Date().getTime() - start));
});
```

Output for the first 20 invocations:
```
2015-08-31 12:03:12.164 Phoenix[2359:123458] Time: 270
2015-08-31 12:03:13.049 Phoenix[2359:123458] Time: 35
2015-08-31 12:03:14.202 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:15.297 Phoenix[2359:123458] Time: 36
2015-08-31 12:03:16.291 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:17.323 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:18.451 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:19.506 Phoenix[2359:123458] Time: 36
2015-08-31 12:03:20.538 Phoenix[2359:123458] Time: 36
2015-08-31 12:03:21.594 Phoenix[2359:123458] Time: 36
2015-08-31 12:03:22.626 Phoenix[2359:123458] Time: 36
2015-08-31 12:03:23.698 Phoenix[2359:123458] Time: 36
2015-08-31 12:03:24.811 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:25.883 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:27.002 Phoenix[2359:123458] Time: 36
2015-08-31 12:03:28.098 Phoenix[2359:123458] Time: 36
2015-08-31 12:03:29.155 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:30.227 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:31.355 Phoenix[2359:123458] Time: 37
2015-08-31 12:03:32.443 Phoenix[2359:123458] Time: 37
```

**Comment by alswl** [comment] 2015-08-31 12:56
Thanks, I will get 'https://github.com/kasper/phoenix/tree/2.0' this, compile and install.
Any progress I will report here.

**Comment by kasper** [comment] 2015-08-31 14:49
@alswl I found one optimisation worth making. We were initialising a new PHApp instance for each access to the window’s app. Now windows keep a reference to their app. This reduced the time by ~10 ms. Probably, not the original cause though.

**Comment by alswl** [comment] 2015-08-31 15:41
Maybe, I use underscore heavily, _.each / _.filter makes it more slow.

**Comment by kasper** [comment] 2015-08-31 18:34
Yes, most certainly they will have an effect, although a four second difference seems a bit weird.

**Comment by kasper** [comment] 2015-09-01 17:15
I’ll close this, since I’m pretty sure `otherWindowsOnSameScreen()` shouldn’t be the cause anymore. Please let me know if you notice the issue again!

**Closed by kasper** 2015-09-01 17:15 UTC
Labels: bug, enhancement
