### ISSUE TITLE
Working with Spaces

### ISSUE THREAD

**Issue by BlueHotDog** [kasper/phoenix#60] opened 2015-12-06 10:08 UTC
does phoenix support osx spaces?

**Comment by kasper** [comment] 2015-12-06 11:56
@BlueHotDog Hi! Unfortunately, as far as I know, OS X doesn’t provide any Accessibility API’s to support spaces.

**Comment by BlueHotDog** [comment] 2015-12-06 11:57
so how SizeUp work?

**Comment by kasper** [comment] 2015-12-06 12:50
@BlueHotDog Does SizeUp support anything fancier than moving windows between spaces? There’s a mouse + keyboard action built into OS X to do just that. Most likely they only trigger that event. We could probably do the same, but unfortunately as far as I know, there isn’t any API to accomplish anything more complex. Rather inconvenient: http://ianyh.com/blog/accessibility-windows-and-spaces-in-os-x/.

**Comment by BlueHotDog** [comment] 2015-12-06 12:56
yeah, probably it's just that, but it's very needed, i would love to drop size-up and move to phoenix, but moving spaces is something i do a lot.

**Comment by kasper** [comment] 2015-12-06 13:20
@BlueHotDog I’ll see what we can do! Thanks for the feedback.

**Comment by jasonm23** [comment] 2015-12-07 02:38
@BlueHotDog it is possible to trigger scripts from Phoenix, so while we don't have it as a built in feature, you can still do it using something like this...

- Add a `~/bin/` folder (or decide where you would like to add user scripts yourself.)

- Add a pair of scripts... 

    ctrl_right

        #!/usr/bin/osascript
        tell application "System Events" to keystroke (ASCII character 29) using control down -- ctrl right

    ctrl_left

        #!/usr/bin/osascript
        tell application "System Events" to keystroke (ASCII character 28) using control down -- ctrl left

- Make them both executable

        chmod +x ctrl*

- Now add calls to these scripts in your Phoenix config using [Command](https://github.com/kasper/phoenix/blob/master/API.md#12-command)

        Command.run("~/bin/ctrl_right")
        Command.run("~/bin/ctrl_left")

    Triggering them how you choose.

**Comment by jasonm23** [comment] 2015-12-07 02:39
Of course, you could always just rebind the Spaces shortcuts in the System Preferences ... that would be easier ;)

**Comment by jasonm23** [comment] 2015-12-07 02:48
@BlueHotDog @kasper Actually it seems that SizeUp will move the window to another space, so not the same as navigating between spaces at all. :(

**Comment by kasper** [comment] 2015-12-07 10:43
@jasonm23 Indeed, the trick is to hold onto the window whilst doing the keyboard shortcut. ;)

**Comment by jasonm23** [comment] 2015-12-07 11:00
Haha, I see...

**Comment by danmactough** [comment] 2015-12-07 11:22
[Spectacle](https://www.spectacleapp.com/) [GitHub](https://github.com/eczarny/spectacle) has figured out how to let you move the current window to the next/previous display. It's pretty sweet. Whenever people see me do it, they're like: "Whoa! How did you do that?!"

<img width="615" alt="untitled" src="https://cloud.githubusercontent.com/assets/357481/11625685/c56aab0a-9caa-11e5-9dfd-01bb41826457.png">

**Comment by kasper** [comment] 2015-12-12 14:07
This is a tricky one since Apple doesn’t provide any official support for Spaces in their API — except for getting a notification when the space changes. That notification doesn’t even contain any details about the change. :(

1. You could use the mouse + keyboard event to trigger the change, but this **requires** that the user has the keyboard shortcut activated in System Settings. This is bound to raise confusion and doesn’t really conform to the idea of this project. http://ianyh.com/blog/accessibility-windows-and-spaces-in-os-x/

2. It seems you can also use **private** API’s to accomplish some support with Spaces. I probably need to test *if and how* they work on El Capitan. Obviously, this can break anytime with internal changes to Apple’s own API’s. https://code.google.com/p/undocumented-goodness/source/browse/trunk/CoreGraphics/CGSPrivate.h

I’m not sure which choice would be the best one, but I’m leaning towards using yet another private API. Sigh.

**Comment by jasonm23** [comment] 2015-12-12 14:35
Private APIs 

D:

**Comment by kasper** [comment] 2015-12-12 15:45
I pushed the milestone to 2.0.2 for this one and released the bug fixes today. I’ll work on this next.

**Comment by kasper** [comment] 2015-12-21 20:51
Some additional resources:

- https://github.com/asmagill/hs._asm.undocumented.spaces/
- https://github.com/NUIKit/CGSInternal/

**Comment by kasper** [comment] 2015-12-22 21:29
I’ve been hacking around and adding support for moving windows between spaces is doable and works rather well. However, I cannot figure out a way to get a list of all the spaces in the order the user has them sorted in Mission Control.

I’ve only been able to get them in the order they have been created. Thus it’s rather hard to do anything useable with the API since you cannot know predictably where you are moving them in relation to the current space. I’ll keep on looking for a solution.

**Comment by BlueHotDog** [comment] 2015-12-23 14:14
Isn't there a way to say move-left,right?

**Comment by BlueHotDog** [comment] 2015-12-23 14:14
and thank you so much for giving it a try

**Comment by kasper** [comment] 2015-12-23 16:04
Not directly, the private APIs are very low-level. You add windows (with IDs) to spaces (with IDs). Without knowing the order of the spaces, you cannot really know what is left or right. However, I have been asking around and I think I finally have the solution. Shouldn’t take too long. :)

**Comment by kasper** [comment] 2015-12-26 22:31
Season’s Greetings! I’ve got some very exiting news, Spaces support has been implemented in Phoenix! Please see the `add-spaces-support`-branch. I decided to add this support using the private APIs. Although this adds some technical debt to this project, I came into the conclusion that Spaces support is rather essential especially on a single display setup. As this is more or less a “hacker” project, it is only suitable to have some support for spaces. I implemented only the most essential aspects, but that being said, in the end the [API](https://github.com/kasper/phoenix/blob/add-spaces-support/API.md#15-space) grew to be a very robust one. I’m rather satisfied with the result. @BlueHotDog Hopefully this should satisfy your needs! :)

Before merging and releasing, I would like people to test the new APIs out. We need to figure out whether these work on Yosemite (10.10). I can confirm everything works as expected on El Capitan. I would also like for people to test the APIs on a multi-screen setup as windows can belong to multiple spaces at the same time. @jasonm23 Would you have time to test the new APIs out?

As the additions are rather substantial, I think we will also bump the version from 2.0.2 to 2.1 for the next release.

**Comment by jasonm23** [comment] 2015-12-27 01:35
I'm on vacation until next week. I will be glad to give the spaces API a few tests when I get back.

**Comment by jasonm23** [comment] 2015-12-27 01:35
Also :+1: kudos

**Comment by kasper** [comment] 2015-12-27 10:23
@jasonm23 Great, have a nice vacation!

**Comment by kasper** [comment] 2016-01-02 21:21
Has anyone had the chance to test this out yet? You can follow the instructions in the README to build from the source: https://github.com/kasper/phoenix#development.

**Comment by jasonm23** [comment] 2016-01-03 06:22
I should be home on Thursday

**Comment by kasper** [comment] 2016-01-24 21:45
@jasonm23 Have you had the chance to take a look at this?

**Comment by jasonm23** [comment] 2016-01-25 08:08
I will look at this today, time permitting

**Comment by jasonm23** [comment] 2016-01-26 01:30
Checking this out right now

**Comment by jasonm23** [comment] 2016-01-26 01:52
Testing: `Window.focusedWindow().spaces()` when there are no spaces

```
26/01/2016 9:49:53.005 am Phoenix[95309]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull unsignedLongValue]: unrecognized selector sent to instance 0x7fff76f2b210'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8bd6703c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff93b0176e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8bd6a0ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff8bcafe24 ___forwarding___ + 1028
	4   CoreFoundation                      0x00007fff8bcaf998 _CF_forwarding_prep_0 + 120
	5   Phoenix                             0x000000010da96083 +[PHSpace spaces] + 507
	6   Phoenix                             0x000000010da962c8 +[PHSpace spacesForWindow:] + 287
	7   CoreFoundation                      0x00007fff8bc3e7bc __invoking___ + 140
	8   CoreFoundation                      0x00007fff8bc3e612 -[NSInvocation invoke] + 290
	9   JavaScriptCore                      0x00007fff8e8e0081 _ZN3JSC24ObjCCallbackFunctionImpl4callEP9JSContextP13OpaqueJSValuemPKPKS3_PS6_ + 417
	10  JavaScriptCore                      0x00007fff8e8dfc16 _ZN3JSCL34objCCallbackFunctionCallAsFunctionEPK15OpaqueJSContextP13OpaqueJSValueS4_mPKPKS3_PS6_ + 262
	11  JavaScriptCore                      0x00007fff8e8e0715 _ZN3JSC19APICallbackFunction4callINS_20ObjCCallbackFunctionEEExPNS_9ExecStateE + 517
	12  JavaScriptCore                      0x00007fff8e50c3d4 _ZN3JSC5LLInt9setUpCallEPNS_9ExecStateEPNS_11InstructionENS_22CodeSpecializationKindENS_7JSValueEPNS_17LLIntCallLinkInfoE + 452
	13  JavaScriptCore                      0x00007fff8e8ccfa7 llint_entry + 22753
	14  JavaScriptCore                      0x00007fff8e8c74a1 callToJavaScript + 311
	15  JavaScriptCore                      0x00007fff8e84b5e3 _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 35
	16  JavaScriptCore                      0x00007fff8e50f0be _ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 462
	17  JavaScriptCore                      0x00007fff8e50eede _ZN3JSC4callEPNS_9ExecStateENS_7JSValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListE + 62
	18  JavaScriptCore                      0x00007fff8e50ee13 JSObjectCallAsFunction + 691
	19  JavaScriptCore                      0x00007fff8e69ac6e -[JSValue callWithArguments:] + 286
	20  Phoenix                             0x000000010da94288 -[PHHandler callWithArguments:] + 263
	21  Phoenix                             0x000000010da9430e -[PHHandler call] + 60
	22  CoreFoundation                      0x00007fff8bd2345c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	23  CoreFoundation                      0x00007fff8bc13634 _CFXNotificationPost + 3140
	24  Foundation                          0x00007fff88b09aa1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	25  Phoenix                             0x000000010da94e94 PHCarbonEventCallback + 249
	26  HIToolbox                           0x00007fff8b7a4b6c _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1260
	27  HIToolbox                           0x00007fff8b7a3fae _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 386
	28  HIToolbox                           0x00007fff8b7b9cb6 SendEventToEventTarget + 40
	29  AppKit                              0x00007fff8f546082 -[NSApplication sendEvent:] + 2104
	30  AppKit                              0x00007fff8f46fb68 -[NSApplication run] + 711
	31  AppKit                              0x00007fff8f3ec244 NSApplicationMain + 1832
	32  libdyld.dylib                       0x00007fff8acac5c9 start + 1
)
```

**Comment by kasper** [comment] 2016-01-26 08:01
@jasonm23 Weird since there should always be at least one space. 10.10 or 10.11?

**Comment by jasonm23** [comment] 2016-01-26 08:14
10.10.5

**Comment by jasonm23** [comment] 2016-01-27 07:29
Note there was an edit "Adding a space, the error still persists."

**Comment by kasper** [comment] 2016-01-27 21:09
Yes, it would seem that the private API behaves differently on 10.10. @jasonm23 If you have any time, would you be able to debug this a bit?

**Comment by jasonm23** [comment] 2016-02-05 01:53
@kasper time has been a bit difficult for me at the moment, but hopefully the next 4 days will be ok.

**Comment by kasper** [comment] 2016-02-05 20:18
@jasonm23 That’s alright! I’m getting a bit hesitant about adding this feature without it working properly. Obviously, the amount of private APIs is a risk. Hopefully this is easy to fix on 10.10. Otherwise this might be left as an experimental feature…

**Comment by jasonm23** [comment] 2016-02-06 02:37
I am always reluctant to use "undocumented" APIs too.

If there were a third party interface library that did the necessary version check and method proxying/mapping it would improve the situation.  

That would be a prerequisite for me, with regards to making it a fully supported feature.

I forget, is there any other open source solution that deals with spaces?

**Comment by kasper** [comment] 2016-02-06 08:31
I don’t think so. Hammerspoon has an unofficial extension for Spaces, but it’s rather experimental as well. Some have implemented partial support for Spaces by either simulating mouse and keyboard events or using the private APIs. Obviously both of these have their shortcomings.

**Comment by shayne** [comment] 2016-02-07 01:19
I've looked into this as well, here's out Silica does it: https://github.com/ianyh/Silica/blob/adcbeda20172c87e25cca9ebb2097bd0b7c8636d/Silica/SIWindow.m#L208

**Comment by kasper** [comment] 2016-02-07 08:49
@shayne Indeed — Silica uses the mouse and keyboard gestures to accomplish moving windows between the nearest Spaces. This however requires that the keyboard shortcuts are activated in System Settings. The good thing is that they are enabled by default, but the bad thing is that if the user has disabled them this would fail silently. :(

**Comment by kasper** [comment] 2016-02-07 08:54
In addition, you would also need to hard code the Spaces order in your configuration. Not very dynamic.

**Comment by alswl** [comment] 2016-03-07 08:18
It seems do not work.

```
keys.push(Phoenix.bind('i', mashCtrl, function() {
  var window = Window.focusedWindow();
  if (!window) return;
  var all = Space.spaces();
  var current = Space.activeSpace();
  var pos = _.indexOf(_.map(all, function(x) { return x.hash(); }), current.hash());
  var prev = all[(pos + 1) % all.length];
  prev.addWindows([window]); // DO NOT WORK
}));
```

My compile version is 27176af

**Comment by alswl** [comment] 2016-03-07 08:23
Oh, I'm sorry, it works.

`addWindows` works like copy window to some space.
I thought it will snip window to some space.

**Comment by kasper** [comment] 2016-03-07 10:29
@alswl Indeed, a window can be in multiple spaces at the same time.

**Comment by alswl** [comment] 2016-03-22 03:43
works for me, thanks.

```
// move window to next space
keys.push(Phoenix.bind('o', mashCtrl, function() {
  var window = Window.focusedWindow();
  if (!window) return;
  var current = Space.activeSpace();
  var spacesInScreen = _.filter(Space.spaces(), function(x) { return x.screen().hash() == current.screen().hash(); });
  var pos = _.indexOf(_.map(spacesInScreen, function(x) { return x.hash(); }), current.hash());
  if (pos + 1 == spacesInScreen.length) return;
  var next = spacesInScreen[pos + 1];
  if (next.hash() == current.hash()) return;
  current.removeWindows([window]);
  next.addWindows([window]);
}));
```

**Comment by kasper** [comment] 2016-03-23 12:55
@alswl Thanks for testing the feature out!

**Comment by kasper** [comment] 2016-03-23 12:59
Spaces support has now finally been merged to master and will be released in the next release 2.1. These features are only supported on El Capitan (10.11) and upwards. If you are willing to get this working on 10.10, please submit a pull request. Thanks!

**Closed by kasper** 2016-03-23 12:59 UTC
Labels: feature

**Comment by kasper** [comment] 2016-03-23 14:18
@alswl By the way, you can use `next()` and `previous()` with Spaces too. Might help your implementation.

**Comment by alswl** [comment] 2016-03-24 02:38
@kasper oh, I see, `Space` implements `Iterable`, thanks.
