### ISSUE TITLE
Phoenix fires no Window events for GitX

### ISSUE THREAD

**Issue by Drarok** [kasper/phoenix#145] opened 2016-10-26 18:01 UTC
- Version: 2.3 (49)
- macOS: 10.11.6

I use [GitX](http://rowanj.github.io/gitx/) regularly, and was hoping to script its windows using Phoenix, but it never fires Window events (I've tried `windowDidFocus` and `windowDidOpen`).

It _does_ fire `appDidLaunch`, and I can iterate its launch-time windows, but that won't help me if I later open a new window.

**Comment by kasper** [comment] 2016-10-26 20:56
@Drarok Hello! App events are global and sent by the system. Window events are part of the Accessibility API. Unfortunately, this means if the app uses custom windows and doesn’t implement support for the events, you will therefore not receive these events from the app. (Or the events fail to register — you can check the Console if Phoenix reports any errors.)

Most apps work just fine, but there are exceptions. Likely this is caused by an upstream issue that would need a fix from GitX.

I guess, as a workaround, you could create a timer and observe the windows for the app to notice changes. Not optimal, but a solution.

**Comment by Drarok** [comment] 2016-10-26 21:11
Thanks for the speedy reply! 

What I ended up doing to work around it was using the `appDidLaunch` and `appDidActivate` events – this still doesn't fix the "opening a new window" issue, but given that most of the time I open a new window from the command-line, activation should be fine _most_ of the time.

Do you know what needs adding to GitX to make it emit these events if I were to fork and create a pull request to add them?

**Comment by kasper** [comment] 2016-10-27 04:52
You’re most welcome!

- Phoenix observes [these](https://github.com/kasper/phoenix/blob/master/Phoenix/PHAXObserver.m#L74-L80) Accessibility API events.
- Custom views must implement the [NSAccessibility](https://developer.apple.com/reference/appkit/nsaccessibility)-protocol to notify accessibility clients.

Basically, if GitX uses custom views that don’t inherit from AppKit objects, it needs to manually post the relevant information when these events happen.

**Comment by kasper** [comment] 2016-11-19 14:27
Closing as invalid since this is most likely an upstream issue.

**Closed by kasper** 2016-11-19 14:27 UTC
Labels: invalid
